### ISSUE TITLE
No output with 8 second clip?

### ISSUE THREAD

**Issue by n8henrie** [Gadersd/whisper-burn#4]
This project fails to provide any output on a different test file (the test file works with whisper, sounds normal when I listen to it, and was created from an m4a via ffmpeg according to [the whisper instructions](https://github.com/openai/whisper/blob/b91c907694f96a3fb9da03d4bbdc83fbcd3a40a4/whisper/audio.py#L46)):

```console
$ ffmpeg -i ../whisper/20220922\ 084923.m4a -ar 16000 -ac 1 -c:a pcm_s16le output.wav
$ cargo run --release output.wav tiny_en
    Running `target/release/whisper output.wav tiny_en`
<|notimestamps|>
Transcribed text: <|notimestamps|>
```

GitHub refuses to allow me to upload a wav file (even base64 encoded as .txt). Not sure what the best way to share is.

**Comment by Gadersd** [comment]
Check the bit depth of your wav file. The code currently assumes a 16 bits bit depth.

**Comment by Gadersd** [comment]
I just added support for other bit depths. It should hopefully work now.

**Comment by n8henrie** [comment]
Works! Thank you, and sorry for the long response time.
